/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-07-14 11:41:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cadastro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-BR\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=0.5\">\r\n");
      out.write("<title>Cadastro</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.mask.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.validation.pt-br.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Fjalla+One&display=swap\"rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/5000ee8fc6.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"js/script.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"js/script_forms.js\" charset=\"utf-8\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		HttpSession hs = request.getSession();
		if(hs.getAttribute("cnpj") == null){
	
      out.write("\r\n");
      out.write("\t<div class=\"pos-f-t \">\r\n");
      out.write("\t\t<div class=\"collapse\" id=\"navbarToggleExternalContent\">\r\n");
      out.write("\t\t\t<div class=\"bg-dark p-2\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item pt-lg-0 pt-3\"><a class=\"nav-link text-white mr-3\" href=\"login.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-dark\">\r\n");
      out.write("\t\t\t<button id=\"hamb\">\r\n");
      out.write("\t\t\t\t<span class=\"hamburguer\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div id=\"mySidebar\" class=\"sidebar\">\r\n");
      out.write("\t\t\t\t<button class=\"close-side\">&times;</button>\r\n");
      out.write("\t\t\t\t<a href=\"index.jsp\"><i class=\"fas fa-home\"></i> HOME</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"login.jsp\"><i class=\"fas fa-house-user\"></i> LOGIN</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"cadastro.jsp\" class=\"active\"><i class=\"fas fa-user-plus\"></i>\r\n");
      out.write("\t\t\t\t\tCADASTRO</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"nav-item\" src=\"icons/logo.png\" width=\"45px\">\r\n");
      out.write("\t\t\t\t\t\teRelations\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"color: white; font-size: 42px; margin-right: 20px\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"login\" class=\"row d-center\">\r\n");
      out.write("\t\t<div class=\"col-xl-6 col-12\">\r\n");
      out.write("\t\t\t<img class=\"img-responsive\" src=\"img/cadastro.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\" col-xl-6 col-12\">\r\n");
      out.write("\t\t\t\t<div class=\"text-center mb-4\">\r\n");
      out.write("\t\t\t\t\t<h2>CADASTRO</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"servlet\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"cnpj\" placeholder=\"CNPJ\" required>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control mr-2\" name=\"nome_empresa\" placeholder=\"Nome da empresa\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t<fieldset class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"tipo\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Comercial\">Comercial</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Industrial\">Industrial</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Rural\">Rural</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"telefone\" placeholder=\"Telefone\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group endereco\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"rua\" placeholder=\"Rua\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"bairro\" placeholder=\"Bairro\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<fieldset class=\"col-xl-2 col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"numero\" placeholder=\"Número\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group endereco\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control mr-2\" name=\"cidade\" placeholder=\"Cidade\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t<fieldset class=\"col-xl-2 col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"estado\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option disabled>UF</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AC\">AC</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AL\">AL</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AP\">AP</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AM\">AM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"BA\">BA</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"CE\">CE</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"DF\">DF</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"ES\">ES</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"GO\">GO</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MA\">MA</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MT\">MT</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MS\">MS</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MG\">MG</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"PA\">PA</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"PB\">PB</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"PR\">PR</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"PE\">PE</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"PI\">PI</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"RJ\">RJ</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"RN\">RN</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"RS\">RS</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"RO\">RO</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"RR\">RR</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"SC\">SC</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"SP\">SP</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"SE\">SE</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"TO\">TO</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t<fieldset class=\"col-xl-2 col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"cep\" placeholder=\"CEP\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"senha\" id=\"senha\" placeholder=\"Senha\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"confirmar_senha\" placeholder=\"Confirme a senha\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t<img name=\"img\" id=\"img-select\" class=\"rounded-circle\" height=\"100px\" width=\"100px\"/>\r\n");
      out.write("                    \t<label for=\"foto\" id=\"lb-image\"><i class=\"fas fa-pencil-alt\"></i></label>\r\n");
      out.write("                    \t<input type=\"file\" name=\"foto\" accept=\".jpg\" id=\"foto\">\r\n");
      out.write("                   \t</div>\r\n");
      out.write("                   \t<div class=\"input-group\">\r\n");
      out.write("     \t\t\t\t\t<textarea rows=\"2\" name=\"descricao\" class=\"form-control\" placeholder=\"Descrição. Exp.: Empresa especializada em fabricação de bebidas\"></textarea>\r\n");
      out.write("                   \t</div>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary \">ACESSAR</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t");

	} else {
		response.sendRedirect("home.jsp");
	}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
