/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-07-14 11:46:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.json.JSONArray;
import org.json.JSONObject;
import model.Conexao;

public final class mensagem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Conexao");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("org.json.JSONArray");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=0.6\">\r\n");
      out.write("<title>Mensagens</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery.js\"></script>\r\n");
      out.write("<script src=\" js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Fjalla+One&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/5000ee8fc6.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script charset=\"utf-8\" src=\"js/script.js\"></script>\r\n");
      out.write("\t<script charset=\"utf-8\" src=\"js/script_mensagem.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");

	HttpSession hs = request.getSession();
	if(hs.getAttribute("cnpj") != null){
	
      out.write("\r\n");
      out.write("\t<div class=\"pos-f-t \">\r\n");
      out.write("\t\t<div class=\"collapse\" id=\"navbarToggleExternalContent\">\r\n");
      out.write("\t\t\t<div class=\"bg-dark p-2\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item pt-lg-0 pt-3\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link text-white mr-3\" href=\"login.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-dark\">\r\n");
      out.write("\t\t\t<button id=\"hamb\">\r\n");
      out.write("\t\t\t\t<span class=\"hamburguer\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div id=\"mySidebar\" class=\"sidebar\">\r\n");
      out.write("\t\t\t\t<button class=\"close-side\">&times;</button>\r\n");
      out.write("\t\t\t\t<a href=\"home.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-home\"></i> FEED\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"perfil.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-user\"></i> PERFIL\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"socios.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-user-friends\"></i> SOCIOS\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"solicitacoes.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-address-book\"></i> SOLICITAÇÕES\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"mensagem.jsp\" class=\"active\">\r\n");
      out.write("                    <i class=\"fas fa-comments\"></i> MENSAGENS\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"agenda.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-calendar-alt\"></i> AGENDA\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"meusprodutos.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-box\"></i> MEUS PRODUTOS\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"pedidos.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-truck\"></i> PEDIDOS\r\n");
      out.write("                </a>\r\n");
      out.write("                <form method=\"POST\" action=\"servlet\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"3\">\r\n");
      out.write("                    <button>\r\n");
      out.write("                        <i class=\"fas fa-sign-out-alt\"></i> SAIR\r\n");
      out.write("                    </button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"logo jusify-content-center\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"nav-item\" src=\"icons/logo.png\" height=\"45px\">eRelation\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"color:white;font-size: 42px;margin-right:20px\">\r\n");
      out.write("\t\t\t\t");

				Conexao conection = new Conexao();
				JSONObject obj = new JSONObject();
				obj.put("cnpj", hs.getAttribute("cnpj"));
				String result = conection.conexao(obj, 18, "svEmpresa");
				JSONObject obVerify = new JSONObject(result);
				if(obVerify.getBoolean("verify")){ out.println("<span class=\"new\"></span>");
				}
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"caixaentrada.jsp\" style=\"color:white;\"><i class=\"fas fa-envelope\"></i></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"content-msn\">\r\n");
      out.write("\t\t<div class=\"side-mensagens\">\r\n");
      out.write("\t\t\t<button class=\"toggle-users\">\r\n");
      out.write("\t\t\t\t<i class=\"fas fa-angle-double-right\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"side-header\">\r\n");
      out.write("\t\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t\t<input type=\"search\" placeholder=\"Search..\" name=\"search\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"list-user\">\r\n");
      out.write("\t\t\t\t");

					conection = new Conexao();
					result = conection.conexao(obj, 5, "svMensagem");

					boolean hasCnpj = false;
					String cnpj = "";
					String empresa = "";
					
					if(!result.isEmpty()){
						JSONArray arr = new JSONArray(result);
	
						for (int i = 0; i < arr.length(); i++) {
							JSONObject ob = arr.getJSONObject(i);
							if (ob.getString("cnpj_conversa").equals(request.getParameter("cnpjDest"))) {
								cnpj = ob.getString("cnpj_conversa");
								empresa = ob.getString("empresa");
								hasCnpj = true;
							}
				
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"user ");
if(ob.getString("cnpj_conversa").equals(request.getParameter("cnpjDest"))){ out.println("active");}
      out.write("\" data-user=\"");
      out.print(ob.getString("cnpj_conversa"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img-user\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-image:url('http://");
out.print(conection.getIp()+":"+conection.getPort()); 
      out.write("/WebServlet/svEmpresa?cnpj=");
      out.print(ob.getString("cnpj_conversa"));
      out.write("')\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"about\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"name\">");
      out.print(ob.getString("empresa"));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"last-hour\">");
      out.print(ob.getString("horario"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"status\"></span>\r\n");
      out.write("\t\t\t\t\t\t");
 if(ob.getInt("number_message") > 0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<span class=\"number-message\">");
      out.print(ob.getInt("number_message"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<span class=\"last-message\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								if (ob.getString("cnpj").equals(hs.getAttribute("cnpj"))) {
										out.println("Você: " + ob.getString("mensagem"));
									} else {
										out.println(ob.getString("mensagem"));
									}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

					}
				}
					if (!hasCnpj && request.getParameter("cnpjDest") != null) {
						conection = new Conexao();
						obj = new JSONObject();
						obj.put("cnpj", request.getParameter("cnpjDest"));
						result = conection.conexao(obj, 3, "svEmpresa");

						obj = new JSONObject(result);
						cnpj = obj.getString("cnpj");
						empresa = obj.getString("empresa");
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"user active\" data-user=\"");
      out.print(obj.getString("cnpj"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img-user\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-image:url('http://");
out.print(conection.getIp()+":"+conection.getPort()); 
      out.write("/WebServlet/svEmpresa?cnpj=");
      out.print(obj.getString("cnpj"));
      out.write("')\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"about\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"name\">");
      out.print(obj.getString("empresa"));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"last-hour\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"status\"></span> <span class=\"last-message\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"chatbox\">\r\n");
      out.write("\t\t\t<div class=\"chat-header\">\r\n");
      out.write("\t\t\t\t<div class=\"img-user\"\r\n");
      out.write("\t\t\t\t\t\t");
if(request.getParameter("cnpjDest") != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-image:url('http://");
      out.print(conection.getIp());
      out.write(':');
      out.print(conection.getPort() );
      out.write("/WebServlet/svEmpresa?cnpj=");
      out.print(request.getParameter("cnpjDest"));
      out.write("');\" \r\n");
      out.write("\t\t\t\t\t\t");
}
      out.write(">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"chat-about\"\r\n");
      out.write("\t\t\t\t\tdata-user=\"");
      out.print(cnpj);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-with\">\r\n");
      out.write("\t\t\t\t\t\tConversando com\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(empresa);
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"status \"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"logs\"></div>\r\n");
      out.write("\t\t\t<div class=\"chat-footer\">\r\n");
      out.write("\t\t\t\t<div class=\"message-submit\">\r\n");
      out.write("\t\t\t\t\t<textarea placeholder=\"Digite aqui a sua mensagem.\" id=\"message\"></textarea>\r\n");
      out.write("\t\t\t\t\t<button id=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-paper-plane\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

	} else {
		response.sendRedirect("index.jsp?e=1002");
	}
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
