/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-07-14 11:46:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import org.json.JSONArray;
import org.json.JSONObject;
import model.Conexao;

public final class pedidos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Conexao");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("org.json.JSONArray");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=0.5\">\r\n");
      out.write("<title>Pedidos</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/5000ee8fc6.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Fjalla+One&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://js.api.here.com/v3/3.1/mapsjs-core.js\"\r\n");
      out.write("\ttype=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"https://js.api.here.com/v3/3.1/mapsjs-service.js\"\r\n");
      out.write("\ttype=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<script charset=\"utf-8\" src=\"js/script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

	HttpSession hs = request.getSession();
	if(hs.getAttribute("cnpj") != null){
		Conexao conection = new Conexao();
		JSONObject obj = new JSONObject();
		obj.put("cnpj", hs.getAttribute("cnpj"));
		String result = conection.conexao(obj, 2,"svMensagem");
		JSONObject obVerify = new JSONObject(result);
	
      out.write("\r\n");
      out.write("\t<div class=\"pos-f-t \">\r\n");
      out.write("\t\t<div class=\"collapse\" id=\"navbarToggleExternalContent\">\r\n");
      out.write("\t\t\t<div class=\"bg-dark p-2\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item pt-lg-0 pt-3\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link text-white mr-3\" href=\"login.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-dark\">\r\n");
      out.write("\t\t\t<button id=\"hamb\">\r\n");
      out.write("\t\t\t\t<span class=\"hamburguer\"></span>\r\n");
      out.write("\t\t\t\t");

					if (obVerify.getBoolean("verify")) {
						out.println("<span class=\"new\"></span>");
					}
				
      out.write("\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div id=\"mySidebar\" class=\"sidebar\">\r\n");
      out.write("\t\t\t\t<button class=\"close-side\">&times;</button>\r\n");
      out.write("\t\t\t\t<a href=\"home.jsp\"> <i class=\"fas fa-home\"></i>\r\n");
      out.write("\t\t\t\t\tFEED\r\n");
      out.write("\t\t\t\t</a> <a href=\"perfil.jsp\"> <i class=\"fas fa-user\"></i> PERFIL\r\n");
      out.write("\t\t\t\t</a> <a href=\"socios.jsp\"> <i class=\"fas fa-user-friends\"></i>\r\n");
      out.write("\t\t\t\t\tSOCIOS\r\n");
      out.write("\t\t\t\t</a> <a href=\"solicitacoes.jsp\"> <i class=\"fas fa-address-book\"></i>\r\n");
      out.write("\t\t\t\t\tSOLICITAÇÕES\r\n");
      out.write("\t\t\t\t</a> <a href=\"mensagem.jsp\"> <i class=\"fas fa-comments\"></i>\r\n");
      out.write("\t\t\t\t\tMENSAGENS ");
 if (obVerify.getBoolean("verify")) { out.println("<span class=\"new\"></span>"); } 
      out.write("\r\n");
      out.write("\t\t\t\t</a> <a href=\"agenda.jsp\"> <i class=\"fas fa-calendar-alt\"></i>\r\n");
      out.write("\t\t\t\t\tAGENDA\r\n");
      out.write("\t\t\t\t</a> <a href=\"meusprodutos.jsp\"> <i class=\"fas fa-box\"></i> MEUS\r\n");
      out.write("\t\t\t\t\tPRODUTOS\r\n");
      out.write("\t\t\t\t</a> <a href=\"pedidos.jsp\" class=\"active\"> <i class=\"fas fa-truck\"></i> PEDIDOS\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<form method=\"POST\" action=\"servlet\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"3\">\r\n");
      out.write("\t\t\t\t\t<button>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-sign-out-alt\"></i> SAIR\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"logo jusify-content-center\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"nav-item\" src=\"icons/logo.png\" height=\"45px\">eRelation\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"color: white; font-size: 42px; margin-right: 20px\">\r\n");
      out.write("\t\t\t\t");

					conection = new Conexao();
					result = conection.conexao(obj, 18, "svEmpresa");
					obVerify = new JSONObject(result);
					if (obVerify.getBoolean("verify")) {
						out.println("<span class=\"new\"></span>");
					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"caixaentrada.jsp\" style=\"color: white;\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-envelope\"></i></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"content col-xl-10 container-fluid\">\r\n");
      out.write("\t\t<nav class=\" nav nav-tabs d-print-none\" id=\"myTab\" role=\"tablist\">\r\n");
      out.write("\t\t\t<a class=\"nav-link active\" id=\"tab1\" data-toggle=\"tab\" href=\"#pedidos2\">\r\n");
      out.write("\t\t\t\tPedidos para mim\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a class=\"nav-link\" id=\"tab2\" data-toggle=\"tab\" href=\"#pedidos1\">\r\n");
      out.write("\t\t\t\tNossos pedidos\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"tab-content\" id=\"myTabContent\">\r\n");
      out.write("\t\t\t<div id=\"pedidos1\" class=\"tab-pane fade show\">\r\n");
      out.write("\t\t\t\t<h2 class=\"text-center mt-5\">NOSSOS PEDIDOS</h2>\r\n");
      out.write("\t\t\t\t<div class=\"pedidos\">\r\n");
      out.write("\t\t\t\t\t");

					conection = new Conexao();
					result = conection.conexao(obj, 5, "svPedidos");
					NumberFormat formatPreco = new DecimalFormat("0.00");
					JSONArray arr;
					SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
					if(!result.isEmpty() && !result.equals("[]")){
						arr = new JSONArray(result);
						for (int i = 0; i < arr.length(); i++) {
							JSONObject ob = arr.getJSONObject(i);
					
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"pedidos\" class=\"col-sm-10 col container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"accordion\" id=\"accordionExample\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body titulo\" id=\"headingTwo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h5>");
      out.print(ob.getString("fornecedor"));
      out.write(" <img src=\"icons/seta.png\"> ");
      out.print(ob.getString("cliente"));
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"progressbar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li ");
if(ob.getInt("status") >= 1) out.println("class=\"active\""); 
      out.write(">AGUARDANDO DATA DE ENTREGA</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li ");
if(ob.getInt("status") >= 2) out.println("class=\"active\""); 
      out.write(">PREPARANDO TRANSPORTE</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li ");
if(ob.getInt("status") >= 3) out.println("class=\"active\""); 
      out.write(">EM TRANSPORTE</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li ");
if(ob.getInt("status") >= 4) out.println("class=\"active\""); 
      out.write(">ENTREGUE</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"content-pedido\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"data-pedido\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><h6>Data do pedido:</h6> ");
      out.print(sdf.format(new SimpleDateFormat("yyyy-MM-dd").parse(ob.getString("data_pedido"))) );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if (ob.has("data_previsao")) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><h6>Data de previsão:</h6> ");
      out.print(sdf.format(new SimpleDateFormat("yyyy-MM-dd").parse(ob.getString("data_previsao"))) );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if (ob.has("data_final")) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><h6>Data de entrega:</h6> ");
      out.print(sdf.format(new SimpleDateFormat("yyyy-MM-dd").parse(ob.getString("data_final"))) );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-map-marker-alt\"></i> ");
      out.print(ob.getString("endereco"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if (ob.getInt("status") == 3) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form action=\"servlet\" method=\"POST\" style=\"float: left;margin-right: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"18\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(ob.getInt("id"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"status\" value=\"");
      out.print(ob.getInt("status") + 1);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\">DEFINIR COMO ENTREGUE</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
										if (ob.getInt("status") <= 3) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form action=\"servlet\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"19\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"hidden\" name=\"id\" value=\"");
      out.print(ob.getInt("id"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\" style=\"\">CANCELAR PEDIDO</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										
									} else {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"far fa-check-circle\" style=\"font-size: 1.5rem;color:#009688;\" aria-hidden=\"true\"></i> PEDIDO ENTREGUE\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-warning collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseItens");
      out.print(ob.getInt("id"));
      out.write("\" aria-expanded=\"false\" aria-controls=\"collapseItens");
      out.print(ob.getInt("id"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-chevron-circle-down\" style=\"font-size: 1.5rem;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse multi-collapse\" id=\"collapseItens");
      out.print(ob.getInt("id"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\" style=\"background-color: white;box-shadow: 0 0 30px 0 rgb(160, 160, 160,0.3);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Itens</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"itens\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										JSONArray array = ob.getJSONArray("itens");
										for (int j = 0; j < array.length(); j++) {
										JSONObject objt = array.getJSONObject(j); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"itens-prod\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><h6>ID:</h6> ");
      out.print(objt.getInt("id_prod"));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><h6>PRODUTO:</h6> ");
      out.print(objt.getString("produto"));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><h6>QNT.:</h6> ");
      out.print(objt.getInt("qnt"));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><h6>VALOR UNITÁRIO:</h6> R$");
      out.print(formatPreco.format(objt.getFloat("valor")));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><h6>SUB-TOTAL:</h6> R$");
      out.print(formatPreco.format(objt.getFloat("valor")*objt.getInt("qnt")));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");

						}
					} else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"empty\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/empty2.png\" class=\"col-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"empty-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1>Ops!</h1>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\tParece que você não realizou nenhum pedido.\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"obs\">\r\n");
      out.write("\t\t\t\t\t\t\t\tObs.: Aqui aparecerão os pedidos feitos por sua empresa. Fique atento na caixa de entrada e habilite as notifcações, elas serâo úteis para você acompanhar os status de seu pedido.\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div id=\"pedidos2\" class=\"tab-pane fade show active\">\r\n");
      out.write("\t\t\t\t<h2 class=\"text-center mt-5\">PEDIDOS PARA MIM</h2>\r\n");
      out.write("\t\t\t\t<div class=\"pedidos\">\r\n");
      out.write("\t\t\t\t\t");

					conection = new Conexao();
					result = conection.conexao(obj, 4, "svPedidos");
					if(!result.isEmpty()){
						arr = new JSONArray(result);
						for (int i = 0; i < arr.length(); i++) {
							JSONObject ob = arr.getJSONObject(i);
					
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"pedidos\" class=\"col-sm-10 col container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"accordion\" id=\"accordionExample\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body titulo\" id=\"headingTwo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h5>");
      out.print(ob.getString("fornecedor"));
      out.write(" <img src=\"icons/seta.png\"> ");
      out.print(ob.getString("cliente"));
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"progressbar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li ");
if(ob.getInt("status") >= 1) out.println("class=\"active\""); 
      out.write(">AGUARDANDO DATA DE ENTREGA</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li ");
if(ob.getInt("status") >= 2) out.println("class=\"active\""); 
      out.write(">PREPARANDO TRANSPORTE</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li ");
if(ob.getInt("status") >= 3) out.println("class=\"active\""); 
      out.write(">EM TRANSPORTE</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li ");
if(ob.getInt("status") >= 4) out.println("class=\"active\""); 
      out.write(">ENTREGUE</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"content-pedido\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"data-pedido\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><h6>Data do pedido:</h6> ");
      out.print(sdf.format(new SimpleDateFormat("yyyy-MM-dd").parse(ob.getString("data_pedido"))));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if (ob.has("data_previsao")) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><h6>Data de previsão:</h6> ");
      out.print(sdf.format(new SimpleDateFormat("yyyy-MM-dd").parse(ob.getString("data_previsao"))));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if (ob.has("data_final")) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><h6>Data de entrega:</h6> ");
      out.print(sdf.format(new SimpleDateFormat("yyyy-MM-dd").parse(ob.getString("data_final"))));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-map-marker-alt\"></i> ");
      out.print(ob.getString("endereco"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									String msg = null;
					
									switch (ob.getInt("status")) {
									case 0:
										msg = "DEFINIR DATA DE ENTREGA";
										break;
									case 1:
										msg = "DEFINIR EM PREPARANDO TRANPORTE";
										break;
									case 2:
										msg = "DEFINIR COMO TRANSPORTANDO";
										break;
									case 4: 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"far fa-check-circle\" style=\"font-size: 1.5rem;color:#009688;\" aria-hidden=\"true\"></i> PEDIDO ENTREGUE\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										break;
									}
									if (ob.getInt("status") < 3) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"servlet\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"18\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(ob.getInt("id"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"status\" value=\"");
      out.print(ob.getInt("status") + 1);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											if (ob.getInt("status") == 0) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"date\" name=\"data_prev\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\">");
      out.print(msg);
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-warning collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseItens");
      out.print(ob.getInt("id"));
      out.write("\" aria-expanded=\"false\" aria-controls=\"collapseItens");
      out.print(ob.getInt("id"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-chevron-circle-down\" style=\"font-size: 1.5rem;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse multi-collapse\" id=\"collapseItens");
      out.print(ob.getInt("id"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\" style=\"background-color: white;box-shadow: 0 0 30px 0 rgb(160, 160, 160,0.3);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Itens</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"itens\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
JSONArray array = ob.getJSONArray("itens");
										for (int j = 0; j < array.length(); j++) {
										JSONObject objt = array.getJSONObject(j); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"itens-prod\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><h6>ID:</h6> ");
      out.print(objt.getInt("id_prod"));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><h6>PRODUTO:</h6> ");
      out.print(objt.getString("produto"));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><h6>QNT.:</h6> ");
      out.print(objt.getInt("qnt"));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><h6>VALOR UNITÁRIO:</h6> R$");
      out.print(formatPreco.format(objt.getFloat("valor")));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><h6>SUB-TOTAL:</h6> R$");
      out.print(formatPreco.format(objt.getFloat("valor")*objt.getInt("qnt")));
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

						}
					} else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"empty\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/empty2.png\" class=\"col-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"empty-body\">\r\n");
      out.write("\t\t\t\t\t\t<h1>Ops!</h1>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tParece que você não possui nenhum novo pedido.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"obs\">\r\n");
      out.write("\t\t\t\t\t\t\tObs.: Aqui aparecerão os pedidos feitos para você. Fique atento na caixa de entrada e habilite as notifcações, elas serâo úteis para você nâo perder nenhum pedido.\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

	} else {
		response.sendRedirect("index.jsp?e=1002");
	}
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
