/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-07-08 12:49:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Conexao;
import org.json.JSONObject;

public final class updateempresa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Conexao");
    _jspx_imports_classes.add("org.json.JSONObject");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=0.5\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.mask.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.validation.pt-br.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Fjalla+One&display=swap\"rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/5000ee8fc6.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"js/script.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"js/script_forms.js\" charset=\"utf-8\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");

		HttpSession hs = request.getSession();

		Conexao conection = new Conexao();
		JSONObject obj = new JSONObject();
		obj.put("cnpj", hs.getAttribute("cnpj"));
		String result = conection.conexao(obj, 2,"svMensagem");
		JSONObject obVerify = new JSONObject(result);
	
      out.write("\r\n");
      out.write("\t<div class=\"pos-f-t \">\r\n");
      out.write("\t\t<div class=\"collapse\" id=\"navbarToggleExternalContent\">\r\n");
      out.write("\t\t\t<div class=\"bg-dark p-2\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item pt-lg-0 pt-3\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link text-white mr-3\" href=\"login.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-dark\">\r\n");
      out.write("\t\t\t<button id=\"hamb\">\r\n");
      out.write("\t\t\t\t<span class=\"hamburguer\"></span>\r\n");
      out.write("\t\t\t\t");

					if (obVerify.getBoolean("verify")) {
						out.println("<span class=\"new\"></span>");
					}
				
      out.write("\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div id=\"mySidebar\" class=\"sidebar\">\r\n");
      out.write("\t\t\t\t<button class=\"close-side\">&times;</button>\r\n");
      out.write("\t\t\t\t<a href=\"home.jsp\"> <i class=\"fas fa-home\"></i>\r\n");
      out.write("\t\t\t\t\tFEED\r\n");
      out.write("\t\t\t\t</a> <a href=\"perfil.jsp\"> <i class=\"fas fa-user\"></i> PERFIL\r\n");
      out.write("\t\t\t\t</a> <a href=\"socios.jsp\"> <i class=\"fas fa-user-friends\"></i>\r\n");
      out.write("\t\t\t\t\tSOCIOS\r\n");
      out.write("\t\t\t\t</a> <a href=\"solicitacoes.jsp\"> <i class=\"fas fa-address-book\"></i>\r\n");
      out.write("\t\t\t\t\tSOLICITAÇÕES\r\n");
      out.write("\t\t\t\t</a> <a href=\"mensagem.jsp\"> <i class=\"fas fa-comments\"></i>\r\n");
      out.write("\t\t\t\t\tMENSAGENS ");
 if (obVerify.getBoolean("verify")) { out.println("<span class=\"new\"></span>"); } 
      out.write("\r\n");
      out.write("\t\t\t\t</a> <a href=\"agenda.jsp\"> <i class=\"fas fa-calendar-alt\"></i>\r\n");
      out.write("\t\t\t\t\tAGENDA\r\n");
      out.write("\t\t\t\t</a> <a href=\"meusprodutos.jsp\"> <i class=\"fas fa-box\"></i> MEUS\r\n");
      out.write("\t\t\t\t\tPRODUTOS\r\n");
      out.write("\t\t\t\t</a> <a href=\"pedidos.jsp\"> <i class=\"fas fa-truck\"></i> PEDIDOS\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<form method=\"POST\" action=\"servlet\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"3\">\r\n");
      out.write("\t\t\t\t\t<button>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-sign-out-alt\"></i> SAIR\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"logo jusify-content-center\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t<img class=\"nav-item\" src=\"icons/logo.png\" height=\"45px\">eRelation\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"color: white; font-size: 42px; margin-right: 20px\">\r\n");
      out.write("\t\t\t\t");

					conection = new Conexao();
					result = conection.conexao(obj, 18, "svEmpresa");
					obVerify = new JSONObject(result);
					if (obVerify.getBoolean("verify")) {
						out.println("<span class=\"new\"></span>");
					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"caixaentrada.jsp\" style=\"color: white;\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-envelope\"></i></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");

	conection = new Conexao();
	result = conection.conexao(obj, 3, "svEmpresa");
	
	JSONObject objs = new JSONObject(result);
	String[] end = objs.getString("endereco").split(", ");
	String[] bairroNum = end[1].split(" - ");
	String[] cidUf = end[2].split(" - ");
      out.write("\r\n");
      out.write("\t<div id=\"login\" class=\"row d-center\">\r\n");
      out.write("\t\t<div class=\" col-xl-6 col-12\">\r\n");
      out.write("\t\t\t\t<div class=\"text-center mb-4\">\r\n");
      out.write("\t\t\t\t\t<h2>ATUALIZAÇÃO</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"servlet\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t<img name=\"img\" id=\"img-select\" class=\"rounded-circle\" height=\"100px\" width=\"100px\" src=\"http://localhost:8080/WebServlet/Servlet?acao=1&cnpj=");
      out.print(objs.getString("cnpj"));
      out.write("\"/>\r\n");
      out.write("                    \t<label for=\"foto\" id=\"lb-image\"><i class=\"fas fa-pencil-alt\"></i></label>\r\n");
      out.write("                    \t<input type=\"file\" name=\"foto\" accept=\".jpg\" id=\"foto\">\r\n");
      out.write("                   \t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("                        \t<input type=\"text\" class=\"form-control mr-2\" name=\"nome_empresa\" placeholder=\"Nome da empresa\" value=\"");
      out.print(objs.getString("empresa"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t<fieldset class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"tipo\" class=\"form-control\">\r\n");
      out.write("                            <option  value=\"Comercial\" ");
if(objs.getString("tipo").equals("Comercial")) out.println("selected");
      out.write(">Comercial</option>\r\n");
      out.write("                            <option value=\"Industrial\" ");
if(objs.getString("tipo").equals("Industrial")) out.println("selected");
      out.write(">Industrial</option>\r\n");
      out.write("                            <option value=\"Rural\" ");
if(objs.getString("tipo").equals("Rural")) out.println("selected");
      out.write(">Rural</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"telefone\" placeholder=\"Telefone\" value=\"");
      out.print(objs.getString("telefone"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group endereco\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"rua\" placeholder=\"Rua\" value=\"");
      out.print(end[0]);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"bairro\" placeholder=\"Bairro\" value=\"");
      out.print(bairroNum[0]);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<fieldset class=\"col-xl-2 col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" name=\"numero\" placeholder=\"Número\" value=\"");
      out.print(bairroNum[1]);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group endereco\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control mr-2\" name=\"cidade\" placeholder=\"Cidade\" value=\"");
      out.print(cidUf[0]);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t<fieldset class=\"col-xl-2 col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"estado\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option disabled>UF</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AC\" ");
if(cidUf[1].equals("AC")) out.println("selected");
      out.write(">AC</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AL\" ");
if(cidUf[1].equals("AL")) out.println("selected");
      out.write(">AL</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AP\" ");
if(cidUf[1].equals("AP")) out.println("selected");
      out.write(">AP</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"AM\" ");
if(cidUf[1].equals("AM")) out.println("selected");
      out.write(">AM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"BA\" ");
if(cidUf[1].equals("BA")) out.println("selected");
      out.write(">BA</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"CE\" ");
if(cidUf[1].equals("CE")) out.println("selected");
      out.write(">CE</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"DF\" ");
if(cidUf[1].equals("DF")) out.println("selected");
      out.write(">DF</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"ES\" ");
if(cidUf[1].equals("ES")) out.println("selected");
      out.write(">ES</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"GO\" ");
if(cidUf[1].equals("GO")) out.println("selected");
      out.write(">GO</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MA\" ");
if(cidUf[1].equals("MA")) out.println("selected");
      out.write(">MA</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MT\" ");
if(cidUf[1].equals("MT")) out.println("selected");
      out.write(">MT</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MS\" ");
if(cidUf[1].equals("MS")) out.println("selected");
      out.write(">MS</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"MG\" ");
if(cidUf[1].equals("MG")) out.println("selected");
      out.write(">MG</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"PA\" ");
if(cidUf[1].equals("PA")) out.println("selected");
      out.write(">PA</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"PB\" ");
if(cidUf[1].equals("PB")) out.println("selected");
      out.write(">PB</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"PR\" ");
if(cidUf[1].equals("PR")) out.println("selected");
      out.write(">PR</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"PE\" ");
if(cidUf[1].equals("PE")) out.println("selected");
      out.write(">PE</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"PI\" ");
if(cidUf[1].equals("PI")) out.println("selected");
      out.write(">PI</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"RJ\" ");
if(cidUf[1].equals("RJ")) out.println("selected");
      out.write(">RJ</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"RN\" ");
if(cidUf[1].equals("RN")) out.println("selected");
      out.write(">RN</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"RS\" ");
if(cidUf[1].equals("RS")) out.println("selected");
      out.write(">RS</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"RO\" ");
if(cidUf[1].equals("RO")) out.println("selected");
      out.write(">RO</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"RR\" ");
if(cidUf[1].equals("RR")) out.println("selected");
      out.write(">RR</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"SC\" ");
if(cidUf[1].equals("SC")) out.println("selected");
      out.write(">SC</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"SP\" ");
if(cidUf[1].equals("SP")) out.println("selected");
      out.write(">SP</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"SE\" ");
if(cidUf[1].equals("SE")) out.println("selected");
      out.write(">SE</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"TO\" ");
if(cidUf[1].equals("TO")) out.println("selected");
      out.write(">TO</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t<fieldset class=\"col-xl-2 col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"cep\" placeholder=\"CEP\" value=\"");
      out.print(end[3]);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                   \t<div class=\"input-group\">\r\n");
      out.write("     \t\t\t\t\t<textarea rows=\"2\" name=\"descricao\" class=\"form-control\" placeholder=\"Descrição. Exp.: Empresa especializada em fabricação de bebidas\">");
if(objs.has("descricao")) out.println(objs.getString("descricao"));
      out.write("</textarea>\r\n");
      out.write("                   \t</div>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary \">CONCLUIR</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xl-6 col-12\">\r\n");
      out.write("\t\t\t<img class=\"img-responsive\" src=\"img/undraw_forms_78yw.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
